import type { Category } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    slug: "electronics",
    description: "Electronic devices and accessories",
    image: "",
    status: "active",
    productCount: 45,
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "cat-2",
    name: "Clothing",
    slug: "clothing",
    description: "Apparel and fashion items",
    image: "",
    status: "active",
    productCount: 120,
    createdAt: "2024-01-20T14:00:00Z",
  },
  {
    id: "cat-3",
    name: "Home & Garden",
    slug: "home-garden",
    description: "Home decor and gardening supplies",
    image: "",
    status: "active",
    productCount: 67,
    createdAt: "2024-02-01T09:15:00Z",
  },
  {
    id: "cat-4",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and outdoor gear",
    image: "",
    status: "active",
    productCount: 38,
    createdAt: "2024-02-10T11:45:00Z",
  },
  {
    id: "cat-5",
    name: "Books & Media",
    slug: "books-media",
    description: "Books, movies, and music",
    image: "",
    status: "inactive",
    productCount: 89,
    createdAt: "2024-02-15T16:30:00Z",
  },
  {
    id: "cat-6",
    name: "Toys & Games",
    slug: "toys-games",
    description: "Toys, games, and hobbies",
    image: "",
    status: "active",
    productCount: 54,
    createdAt: "2024-03-01T08:00:00Z",
  },
  {
    id: "cat-7",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Health and beauty products",
    image: "",
    status: "active",
    productCount: 72,
    createdAt: "2024-03-05T13:20:00Z",
  },
  {
    id: "cat-8",
    name: "Food & Beverages",
    slug: "food-beverages",
    description: "Food items and beverages",
    image: "",
    status: "active",
    productCount: 95,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "cat-9",
    name: "Automotive",
    slug: "automotive",
    description: "Automotive parts and accessories",
    image: "",
    status: "inactive",
    productCount: 28,
    createdAt: "2024-03-15T15:45:00Z",
  },
  {
    id: "cat-10",
    name: "Office Supplies",
    slug: "office-supplies",
    description: "Office and school supplies",
    image: "",
    status: "active",
    productCount: 41,
    createdAt: "2024-03-20T09:30:00Z",
  },
  {
    id: "cat-11",
    name: "Pet Supplies",
    slug: "pet-supplies",
    description: "Pet food and accessories",
    image: "",
    status: "active",
    productCount: 33,
    createdAt: "2024-04-01T11:00:00Z",
  },
  {
    id: "cat-12",
    name: "Jewelry & Watches",
    slug: "jewelry-watches",
    description: "Fine jewelry and timepieces",
    image: "",
    status: "active",
    productCount: 19,
    createdAt: "2024-04-05T14:15:00Z",
  },
  {
    id: "cat-13",
    name: "Musical Instruments",
    slug: "musical-instruments",
    description: "Instruments and audio equipment",
    image: "",
    status: "inactive",
    productCount: 15,
    createdAt: "2024-04-10T10:45:00Z",
  },
  {
    id: "cat-14",
    name: "Baby & Kids",
    slug: "baby-kids",
    description: "Baby products and kids essentials",
    image: "",
    status: "active",
    productCount: 48,
    createdAt: "2024-04-15T16:00:00Z",
  },
  {
    id: "cat-15",
    name: "Tools & Hardware",
    slug: "tools-hardware",
    description: "DIY tools and hardware supplies",
    image: "",
    status: "active",
    productCount: 62,
    createdAt: "2024-04-20T08:30:00Z",
  },
];
