import type { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Wireless Bluetooth Headphones",
    sku: "WBH-001",
    categoryId: "cat-1",
    categoryName: "Electronics",
    image: "",
    description: "Premium wireless headphones with noise cancellation",
    userPrice: 79.99,
    franchisePrice: 59.99,
    bulkPrice: 49.99,
    minOrder: 10,
    maxOrder: 500,
    status: "active",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod-2",
    name: "Smart Fitness Watch",
    sku: "SFW-002",
    categoryId: "cat-1",
    categoryName: "Electronics",
    image: "",
    description: "Advanced fitness tracking smartwatch",
    userPrice: 199.99,
    franchisePrice: 149.99,
    bulkPrice: 129.99,
    minOrder: 5,
    maxOrder: 200,
    status: "active",
    createdAt: "2024-01-20T14:00:00Z",
  },
  {
    id: "prod-3",
    name: "Cotton Crew Neck T-Shirt",
    sku: "CCT-003",
    categoryId: "cat-2",
    categoryName: "Clothing",
    image: "",
    description: "100% organic cotton comfortable t-shirt",
    userPrice: 24.99,
    franchisePrice: 18.99,
    bulkPrice: 14.99,
    minOrder: 50,
    maxOrder: 1000,
    status: "active",
    createdAt: "2024-02-01T09:15:00Z",
  },
  {
    id: "prod-4",
    name: "Denim Jacket",
    sku: "DJ-004",
    categoryId: "cat-2",
    categoryName: "Clothing",
    image: "",
    description: "Classic denim jacket with modern fit",
    userPrice: 89.99,
    franchisePrice: 69.99,
    bulkPrice: 59.99,
    minOrder: 20,
    maxOrder: 300,
    status: "active",
    createdAt: "2024-02-10T11:45:00Z",
  },
  {
    id: "prod-5",
    name: "Ceramic Plant Pot Set",
    sku: "CPPS-005",
    categoryId: "cat-3",
    categoryName: "Home & Garden",
    image: "",
    description: "Beautiful ceramic pots for indoor plants",
    userPrice: 34.99,
    franchisePrice: 26.99,
    bulkPrice: 21.99,
    minOrder: 15,
    maxOrder: 250,
    status: "active",
    createdAt: "2024-02-15T16:30:00Z",
  },
  {
    id: "prod-6",
    name: "Garden Tool Kit",
    sku: "GTK-006",
    categoryId: "cat-3",
    categoryName: "Home & Garden",
    image: "",
    description: "Complete gardening tool set",
    userPrice: 49.99,
    franchisePrice: 37.99,
    bulkPrice: 29.99,
    minOrder: 10,
    maxOrder: 150,
    status: "inactive",
    createdAt: "2024-03-01T08:00:00Z",
  },
  {
    id: "prod-7",
    name: "Yoga Mat Premium",
    sku: "YMP-007",
    categoryId: "cat-4",
    categoryName: "Sports & Outdoors",
    image: "",
    description: "Non-slip premium yoga mat",
    userPrice: 39.99,
    franchisePrice: 29.99,
    bulkPrice: 24.99,
    minOrder: 20,
    maxOrder: 400,
    status: "active",
    createdAt: "2024-03-05T13:20:00Z",
  },
  {
    id: "prod-8",
    name: "Camping Tent 4-Person",
    sku: "CT4-008",
    categoryId: "cat-4",
    categoryName: "Sports & Outdoors",
    image: "",
    description: "Waterproof 4-person camping tent",
    userPrice: 149.99,
    franchisePrice: 119.99,
    bulkPrice: 99.99,
    minOrder: 5,
    maxOrder: 100,
    status: "active",
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "prod-9",
    name: "Bestseller Novel Collection",
    sku: "BNC-009",
    categoryId: "cat-5",
    categoryName: "Books & Media",
    image: "",
    description: "Set of 5 bestselling novels",
    userPrice: 59.99,
    franchisePrice: 44.99,
    bulkPrice: 36.99,
    minOrder: 10,
    maxOrder: 200,
    status: "inactive",
    createdAt: "2024-03-15T15:45:00Z",
  },
  {
    id: "prod-10",
    name: "Board Game Strategy Set",
    sku: "BGS-010",
    categoryId: "cat-6",
    categoryName: "Toys & Games",
    image: "",
    description: "Collection of strategy board games",
    userPrice: 44.99,
    franchisePrice: 33.99,
    bulkPrice: 27.99,
    minOrder: 12,
    maxOrder: 180,
    status: "active",
    createdAt: "2024-03-20T09:30:00Z",
  },
  {
    id: "prod-11",
    name: "Organic Face Cream",
    sku: "OFC-011",
    categoryId: "cat-7",
    categoryName: "Health & Beauty",
    image: "",
    description: "Natural organic moisturizing face cream",
    userPrice: 29.99,
    franchisePrice: 22.99,
    bulkPrice: 18.99,
    minOrder: 25,
    maxOrder: 500,
    status: "active",
    createdAt: "2024-04-01T11:00:00Z",
  },
  {
    id: "prod-12",
    name: "Premium Coffee Beans",
    sku: "PCB-012",
    categoryId: "cat-8",
    categoryName: "Food & Beverages",
    image: "",
    description: "Single origin arabica coffee beans",
    userPrice: 19.99,
    franchisePrice: 14.99,
    bulkPrice: 11.99,
    minOrder: 30,
    maxOrder: 600,
    status: "active",
    createdAt: "2024-04-05T14:15:00Z",
  },
  {
    id: "prod-13",
    name: "Car Phone Mount",
    sku: "CPM-013",
    categoryId: "cat-9",
    categoryName: "Automotive",
    image: "",
    description: "Universal car phone holder mount",
    userPrice: 14.99,
    franchisePrice: 10.99,
    bulkPrice: 8.99,
    minOrder: 40,
    maxOrder: 800,
    status: "inactive",
    createdAt: "2024-04-10T10:45:00Z",
  },
  {
    id: "prod-14",
    name: "Executive Desk Organizer",
    sku: "EDO-014",
    categoryId: "cat-10",
    categoryName: "Office Supplies",
    image: "",
    description: "Premium bamboo desk organizer",
    userPrice: 27.99,
    franchisePrice: 20.99,
    bulkPrice: 16.99,
    minOrder: 18,
    maxOrder: 300,
    status: "active",
    createdAt: "2024-04-15T16:00:00Z",
  },
  {
    id: "prod-15",
    name: "Dog Training Leash",
    sku: "DTL-015",
    categoryId: "cat-11",
    categoryName: "Pet Supplies",
    image: "",
    description: "Heavy-duty reflective dog leash",
    userPrice: 18.99,
    franchisePrice: 13.99,
    bulkPrice: 10.99,
    minOrder: 25,
    maxOrder: 400,
    status: "active",
    createdAt: "2024-04-20T08:30:00Z",
  },
  {
    id: "prod-16",
    name: "Silver Chain Necklace",
    sku: "SCN-016",
    categoryId: "cat-12",
    categoryName: "Jewelry & Watches",
    image: "",
    description: "Sterling silver chain necklace",
    userPrice: 69.99,
    franchisePrice: 52.99,
    bulkPrice: 42.99,
    minOrder: 8,
    maxOrder: 120,
    status: "active",
    createdAt: "2024-05-01T12:00:00Z",
  },
  {
    id: "prod-17",
    name: "Acoustic Guitar Starter",
    sku: "AGS-017",
    categoryId: "cat-13",
    categoryName: "Musical Instruments",
    image: "",
    description: "Beginner acoustic guitar package",
    userPrice: 129.99,
    franchisePrice: 99.99,
    bulkPrice: 84.99,
    minOrder: 4,
    maxOrder: 60,
    status: "inactive",
    createdAt: "2024-05-05T15:30:00Z",
  },
  {
    id: "prod-18",
    name: "Baby Stroller Deluxe",
    sku: "BSD-018",
    categoryId: "cat-14",
    categoryName: "Baby & Kids",
    image: "",
    description: "All-terrain luxury baby stroller",
    userPrice: 299.99,
    franchisePrice: 229.99,
    bulkPrice: 189.99,
    minOrder: 3,
    maxOrder: 50,
    status: "active",
    createdAt: "2024-05-10T09:00:00Z",
  },
  {
    id: "prod-19",
    name: "Power Drill Set",
    sku: "PDS-019",
    categoryId: "cat-15",
    categoryName: "Tools & Hardware",
    image: "",
    description: "Cordless power drill with accessories",
    userPrice: 89.99,
    franchisePrice: 68.99,
    bulkPrice: 56.99,
    minOrder: 8,
    maxOrder: 100,
    status: "active",
    createdAt: "2024-05-15T14:45:00Z",
  },
  {
    id: "prod-20",
    name: "LED Desk Lamp",
    sku: "LDL-020",
    categoryId: "cat-1",
    categoryName: "Electronics",
    image: "",
    description: "Adjustable LED desk lamp with USB charging",
    userPrice: 34.99,
    franchisePrice: 25.99,
    bulkPrice: 20.99,
    minOrder: 15,
    maxOrder: 250,
    status: "active",
    createdAt: "2024-05-20T11:15:00Z",
  },
];
